[project]
name = "mini-chess"
version = "0.1.0"
description = "Group Project for CSD311-Artificial Intelligence"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.3.5",
    "pydantic>=2.12.4",
]
